name: Version & Build

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    
    steps:

      - name: Copy data
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5

      - name: Install dependencies
        run: yarn add semantic-release @semantic-release/git @semantic-release/github

      - name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}
      
      - name: set env
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: |
            paschendale/scope-auth:latest
            paschendale/scope-auth:${{ env.VERSION }}